# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_type', models.CharField(choices=[(b'to', b'To'), (b'cc', b'Cc'), (b'bcc', b'Bcc')], max_length=5)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FromAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('alternative_from', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('from_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_responses.FromAddress', verbose_name=b'From')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_responses.Response'),
        ),
    ]
